### ISSUE TITLE
Implement boss randomizer ROM side

### ISSUE THREAD

**Issue by cassidoxa** [dashrando/dash-template-asm#10]
For boss randomizer we need to not only shuffle boss rooms but have the ability to place multiple instances of any boss. At a high level this will involve refactoring how the save data is handled for initializing rooms with alive or dead bosses, figuring out how to handle the PLMs for items in duplicate post-boss item rooms (which may involve reworking how items are handled entirely,) turning on wrecked ship for an arbitrary boss at that location but not for Phantoon elsewhere, and handling the G4 statue.

We can use the animal surprise as a reference for initializing an alive-boss room. I think this will mostly involved either carving out some buffers with a length of 4, possibly repurposing the existing boss and boss-room related save data, and hooking into door loading and boss defeat code.

**Comment by MassHesteria** [comment]
This is pretty close to being done on canary. I added copies of each boss room to each area and introduced new PLM variables. We need to make sure it works properly with saving though.
