### ISSUE TITLE
Music change not quite right for East Maridia Highway

### ISSUE THREAD

**Issue by MassHesteria** [dashrando/dash-template-asm#21]
I've noticed that when I go through the East Maridia Highway door, it doesn't always change music until you drop into the room below it. Seems worse going from LN for some reason.

**Comment by MassHesteria** [comment]
Noticed it again this morning when going from G4 to East Maridia Highway

**Comment by Schmo** [comment]
The issue seemed to be only when coming from the portal door, when coming from the elevator door it was fine. Just added the appropriate music for this room into the music.asm section. This is now fixed in canary.
