### ISSUE TITLE
Hook back up the pause screen map

### ISSUE THREAD

**Issue by MassHesteria** [dashrando/dash-template-asm#39]
The feedback we've gotten is that the pause screen map is useful for things like checking to see if you visited an item location or saved. We saw runners do this at SGL where "seed bleed" is a big issue. There's lots of talk about cool stuff we can do with the pause screen map, but step one is to get it back to vanilla. Additionally issues will be filed for any other features.

**Comment by cassidoxa** [comment]
This is mostly done. We still need to figure out how boss rooms will work on the map and resolve any potential issues with that. I suspect there may be some problems with coordinates that will need to be handled there regardless of the solution as long as the area remains vanilla and no changes are made to the vanilla map position tracking/marking code.

**Comment by MassHesteria** [comment]
I'm filing another issue to get the Shifted Boss rooms handled on the map
