### ISSUE TITLE
Fix rainbow beam damage on HUD

### ISSUE THREAD

**Issue by MassHesteria** [dashrando/dash-template-asm#7]
The beam damage on the HUD doesn't update properly after receiving rainbow beam. We should either show the correct value or stop drawing a value. Could make the case for either so it might make more sense to do whichever is easier.

**Comment by cassidoxa** [comment]
Updated this to draw blank tiles after Hyper Beam has been acquired for now in the item-counters branch. Hyper beam damage is 1000 but we currently only have three tiles for digits here with the remaining three used for new DASH item icons. The white separator line also uses a tile that could be reclaimed if we wanted to get rid of it (but not necessarily just to draw 1000 for Hyper Beam damage.)

**Comment by MassHesteria** [comment]
Good enough for now.
